#############################################################################
# Makefile for building: pvp
# Generated by qmake (3.1) (Qt 5.9.2)
# Project:  pvp.pro
# Template: app
# Command: /src/qt5.9.2/bin/qmake -o Makefile pvp.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../qt5.9.2/include -I../../../qt5.9.2/include/QtGui -I../../../qt5.9.2/include/QtCore -I. -isystem /usr/include/libdrm -I../../../qt5.9.2/mkspecs/linux-g++-64
QMAKE         = /src/qt5.9.2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /src/qt5.9.2/bin/qmake -install qinstall
QINSTALL_PROGRAM = /src/qt5.9.2/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = pvp1.0.0
DISTDIR = /src/github/pvpqt/pvp/.tmp/pvp1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/src/qt5.9.2/lib
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/src/qt5.9.2/lib -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = clusteranalysis.cpp \
		main.cpp \
		pvp.cpp \
		pvpanalysis.cpp \
		sasfiles.cpp \
		vectorutils.cpp 
OBJECTS       = clusteranalysis.o \
		main.o \
		pvp.o \
		pvpanalysis.o \
		sasfiles.o \
		vectorutils.o
DIST          = ../../../qt5.9.2/mkspecs/features/spec_pre.prf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/unix.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/linux.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/sanitize.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/gcc-base.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/gcc-base-unix.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/g++-base.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/g++-unix.conf \
		../../../qt5.9.2/mkspecs/qconfig.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3danimation.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dcore.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dextras.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dinput.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquick.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3drender.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_charts.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_charts_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_core.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_core_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_dbus.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_designer.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_designer_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_gamepad.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_gui.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_gui_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_help.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_help_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_location.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_location_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_multimedia.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_network.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_network_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_networkauth.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_nfc.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_positioning.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_purchasing.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qml.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qml_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qmltest.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quick.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quick_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_repparser.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_script.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_script_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_scripttools.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_scxml.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_sensors.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_serialbus.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_serialport.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_sql.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_sql_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_svg.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_svg_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_uitools.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_webchannel.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_websockets.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_x11extras.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xml.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xml_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../qt5.9.2/mkspecs/features/qt_functions.prf \
		../../../qt5.9.2/mkspecs/features/qt_config.prf \
		../../../qt5.9.2/mkspecs/linux-g++-64/qmake.conf \
		../../../qt5.9.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../qt5.9.2/mkspecs/features/exclusive_builds.prf \
		../../../qt5.9.2/mkspecs/features/toolchain.prf \
		../../../qt5.9.2/mkspecs/features/default_pre.prf \
		../../../qt5.9.2/mkspecs/features/resolve_config.prf \
		../../../qt5.9.2/mkspecs/features/default_post.prf \
		../../../qt5.9.2/mkspecs/features/warn_on.prf \
		../../../qt5.9.2/mkspecs/features/qt.prf \
		../../../qt5.9.2/mkspecs/features/resources.prf \
		../../../qt5.9.2/mkspecs/features/moc.prf \
		../../../qt5.9.2/mkspecs/features/unix/opengl.prf \
		../../../qt5.9.2/mkspecs/features/unix/thread.prf \
		../../../qt5.9.2/mkspecs/features/qmake_use.prf \
		../../../qt5.9.2/mkspecs/features/file_copies.prf \
		../../../qt5.9.2/mkspecs/features/testcase_targets.prf \
		../../../qt5.9.2/mkspecs/features/exceptions.prf \
		../../../qt5.9.2/mkspecs/features/yacc.prf \
		../../../qt5.9.2/mkspecs/features/lex.prf \
		pvp.pro clusteranalysis.h \
		pvp.h \
		pvpanalysis.h \
		sasfiles.h \
		vectorutils.h clusteranalysis.cpp \
		main.cpp \
		pvp.cpp \
		pvpanalysis.cpp \
		sasfiles.cpp \
		vectorutils.cpp
QMAKE_TARGET  = pvp
DESTDIR       = 
TARGET        = pvp


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pvp.pro ../../../qt5.9.2/mkspecs/linux-g++-64/qmake.conf ../../../qt5.9.2/mkspecs/features/spec_pre.prf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/unix.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/linux.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/sanitize.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/gcc-base.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/gcc-base-unix.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/g++-base.conf \
		../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/g++-unix.conf \
		../../../qt5.9.2/mkspecs/qconfig.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3danimation.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dcore.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dextras.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dinput.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquick.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3drender.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_charts.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_charts_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_concurrent.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_core.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_core_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_dbus.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_designer.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_designer_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_gamepad.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_gui.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_gui_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_help.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_help_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_location.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_location_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_multimedia.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_network.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_network_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_networkauth.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_nfc.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_opengl.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_positioning.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_printsupport.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_purchasing.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qml.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qml_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qmltest.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quick.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quick_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_repparser.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_script.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_script_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_scripttools.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_scxml.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_sensors.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_serialbus.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_serialport.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_sql.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_sql_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_svg.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_svg_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_testlib.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_uitools.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_webchannel.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_websockets.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_widgets.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_x11extras.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xml.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xml_private.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../qt5.9.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../qt5.9.2/mkspecs/features/qt_functions.prf \
		../../../qt5.9.2/mkspecs/features/qt_config.prf \
		../../../qt5.9.2/mkspecs/linux-g++-64/qmake.conf \
		../../../qt5.9.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../qt5.9.2/mkspecs/features/exclusive_builds.prf \
		../../../qt5.9.2/mkspecs/features/toolchain.prf \
		../../../qt5.9.2/mkspecs/features/default_pre.prf \
		../../../qt5.9.2/mkspecs/features/resolve_config.prf \
		../../../qt5.9.2/mkspecs/features/default_post.prf \
		../../../qt5.9.2/mkspecs/features/warn_on.prf \
		../../../qt5.9.2/mkspecs/features/qt.prf \
		../../../qt5.9.2/mkspecs/features/resources.prf \
		../../../qt5.9.2/mkspecs/features/moc.prf \
		../../../qt5.9.2/mkspecs/features/unix/opengl.prf \
		../../../qt5.9.2/mkspecs/features/unix/thread.prf \
		../../../qt5.9.2/mkspecs/features/qmake_use.prf \
		../../../qt5.9.2/mkspecs/features/file_copies.prf \
		../../../qt5.9.2/mkspecs/features/testcase_targets.prf \
		../../../qt5.9.2/mkspecs/features/exceptions.prf \
		../../../qt5.9.2/mkspecs/features/yacc.prf \
		../../../qt5.9.2/mkspecs/features/lex.prf \
		pvp.pro \
		../../../qt5.9.2/lib/libQt5Gui.prl \
		../../../qt5.9.2/lib/libQt5Core.prl
	$(QMAKE) -o Makefile pvp.pro
../../../qt5.9.2/mkspecs/features/spec_pre.prf:
../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/unix.conf:
../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/linux.conf:
../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/sanitize.conf:
../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/gcc-base.conf:
../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/gcc-base-unix.conf:
../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/g++-base.conf:
../../../qt-everywhere-opensource-src-5.9.2/mkspecs/common/g++-unix.conf:
../../../qt5.9.2/mkspecs/qconfig.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3danimation.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dcore.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dextras.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dinput.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dlogic.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquick.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3drender.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_3drender_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_bluetooth.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_charts.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_charts_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_concurrent.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_core.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_core_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_datavisualization.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_dbus.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_dbus_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_designer.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_designer_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_gamepad.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_gui.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_gui_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_help.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_help_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_input_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_location.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_location_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_multimedia.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_network.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_network_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_networkauth.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_nfc.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_nfc_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_opengl.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_opengl_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_openglextensions.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_positioning.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_positioning_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_printsupport.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_purchasing.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_qml.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_qml_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_qmltest.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_quick.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_quick_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_repparser.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_repparser_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_script.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_script_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_scripttools.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_scxml.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_scxml_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_sensors.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_sensors_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_serialbus.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_serialport.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_serialport_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_service_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_sql.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_sql_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_svg.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_svg_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_testlib.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_testlib_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_texttospeech.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_uiplugin.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_uitools.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_uitools_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_webchannel.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_websockets.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_websockets_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_widgets.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_widgets_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_x11extras.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_xml.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_xml_private.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../qt5.9.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../qt5.9.2/mkspecs/features/qt_functions.prf:
../../../qt5.9.2/mkspecs/features/qt_config.prf:
../../../qt5.9.2/mkspecs/linux-g++-64/qmake.conf:
../../../qt5.9.2/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../qt5.9.2/mkspecs/features/exclusive_builds.prf:
../../../qt5.9.2/mkspecs/features/toolchain.prf:
../../../qt5.9.2/mkspecs/features/default_pre.prf:
../../../qt5.9.2/mkspecs/features/resolve_config.prf:
../../../qt5.9.2/mkspecs/features/default_post.prf:
../../../qt5.9.2/mkspecs/features/warn_on.prf:
../../../qt5.9.2/mkspecs/features/qt.prf:
../../../qt5.9.2/mkspecs/features/resources.prf:
../../../qt5.9.2/mkspecs/features/moc.prf:
../../../qt5.9.2/mkspecs/features/unix/opengl.prf:
../../../qt5.9.2/mkspecs/features/unix/thread.prf:
../../../qt5.9.2/mkspecs/features/qmake_use.prf:
../../../qt5.9.2/mkspecs/features/file_copies.prf:
../../../qt5.9.2/mkspecs/features/testcase_targets.prf:
../../../qt5.9.2/mkspecs/features/exceptions.prf:
../../../qt5.9.2/mkspecs/features/yacc.prf:
../../../qt5.9.2/mkspecs/features/lex.prf:
pvp.pro:
../../../qt5.9.2/lib/libQt5Gui.prl:
../../../qt5.9.2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile pvp.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../qt5.9.2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents clusteranalysis.h pvp.h pvpanalysis.h sasfiles.h vectorutils.h $(DISTDIR)/
	$(COPY_FILE) --parents clusteranalysis.cpp main.cpp pvp.cpp pvpanalysis.cpp sasfiles.cpp vectorutils.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../qt5.9.2/mkspecs/features/data/dummy.cpp
	g++ -m64 -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../qt5.9.2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

clusteranalysis.o: clusteranalysis.cpp clusteranalysis.h \
		../../../qt5.9.2/include/QtCore/QtCore \
		../../../qt5.9.2/include/QtCore/QtCoreDepends \
		../../../qt5.9.2/include/QtCore/qglobal.h \
		../../../qt5.9.2/include/QtCore/qconfig-bootstrapped.h \
		../../../qt5.9.2/include/QtCore/qconfig.h \
		../../../qt5.9.2/include/QtCore/qtcore-config.h \
		../../../qt5.9.2/include/QtCore/qsystemdetection.h \
		../../../qt5.9.2/include/QtCore/qprocessordetection.h \
		../../../qt5.9.2/include/QtCore/qcompilerdetection.h \
		../../../qt5.9.2/include/QtCore/qtypeinfo.h \
		../../../qt5.9.2/include/QtCore/qsysinfo.h \
		../../../qt5.9.2/include/QtCore/qlogging.h \
		../../../qt5.9.2/include/QtCore/qflags.h \
		../../../qt5.9.2/include/QtCore/qatomic.h \
		../../../qt5.9.2/include/QtCore/qbasicatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_bootstrap.h \
		../../../qt5.9.2/include/QtCore/qgenericatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_cxx11.h \
		../../../qt5.9.2/include/QtCore/qatomic_msvc.h \
		../../../qt5.9.2/include/QtCore/qglobalstatic.h \
		../../../qt5.9.2/include/QtCore/qmutex.h \
		../../../qt5.9.2/include/QtCore/qnumeric.h \
		../../../qt5.9.2/include/QtCore/qversiontagging.h \
		../../../qt5.9.2/include/QtCore/qabstractanimation.h \
		../../../qt5.9.2/include/QtCore/qobject.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs.h \
		../../../qt5.9.2/include/QtCore/qnamespace.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs_impl.h \
		../../../qt5.9.2/include/QtCore/qstring.h \
		../../../qt5.9.2/include/QtCore/qchar.h \
		../../../qt5.9.2/include/QtCore/qbytearray.h \
		../../../qt5.9.2/include/QtCore/qrefcount.h \
		../../../qt5.9.2/include/QtCore/qarraydata.h \
		../../../qt5.9.2/include/QtCore/qstringbuilder.h \
		../../../qt5.9.2/include/QtCore/qlist.h \
		../../../qt5.9.2/include/QtCore/qalgorithms.h \
		../../../qt5.9.2/include/QtCore/qiterator.h \
		../../../qt5.9.2/include/QtCore/qhashfunctions.h \
		../../../qt5.9.2/include/QtCore/qpair.h \
		../../../qt5.9.2/include/QtCore/qbytearraylist.h \
		../../../qt5.9.2/include/QtCore/qstringlist.h \
		../../../qt5.9.2/include/QtCore/qregexp.h \
		../../../qt5.9.2/include/QtCore/qstringmatcher.h \
		../../../qt5.9.2/include/QtCore/qcoreevent.h \
		../../../qt5.9.2/include/QtCore/qscopedpointer.h \
		../../../qt5.9.2/include/QtCore/qmetatype.h \
		../../../qt5.9.2/include/QtCore/qvarlengtharray.h \
		../../../qt5.9.2/include/QtCore/qcontainerfwd.h \
		../../../qt5.9.2/include/QtCore/qobject_impl.h \
		../../../qt5.9.2/include/QtCore/qabstracteventdispatcher.h \
		../../../qt5.9.2/include/QtCore/qeventloop.h \
		../../../qt5.9.2/include/QtCore/qabstractitemmodel.h \
		../../../qt5.9.2/include/QtCore/qvariant.h \
		../../../qt5.9.2/include/QtCore/qmap.h \
		../../../qt5.9.2/include/QtCore/qdebug.h \
		../../../qt5.9.2/include/QtCore/qhash.h \
		../../../qt5.9.2/include/QtCore/qtextstream.h \
		../../../qt5.9.2/include/QtCore/qiodevice.h \
		../../../qt5.9.2/include/QtCore/qlocale.h \
		../../../qt5.9.2/include/QtCore/qshareddata.h \
		../../../qt5.9.2/include/QtCore/qvector.h \
		../../../qt5.9.2/include/QtCore/qpoint.h \
		../../../qt5.9.2/include/QtCore/qset.h \
		../../../qt5.9.2/include/QtCore/qcontiguouscache.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer_impl.h \
		../../../qt5.9.2/include/QtCore/qabstractnativeeventfilter.h \
		../../../qt5.9.2/include/QtCore/qabstractproxymodel.h \
		../../../qt5.9.2/include/QtCore/qabstractstate.h \
		../../../qt5.9.2/include/QtCore/qabstracttransition.h \
		../../../qt5.9.2/include/QtCore/qanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qarraydataops.h \
		../../../qt5.9.2/include/QtCore/qarraydatapointer.h \
		../../../qt5.9.2/include/QtCore/qbasictimer.h \
		../../../qt5.9.2/include/QtCore/qbitarray.h \
		../../../qt5.9.2/include/QtCore/qbuffer.h \
		../../../qt5.9.2/include/QtCore/qbytearraymatcher.h \
		../../../qt5.9.2/include/QtCore/qcache.h \
		../../../qt5.9.2/include/QtCore/qcollator.h \
		../../../qt5.9.2/include/QtCore/qcommandlineoption.h \
		../../../qt5.9.2/include/QtCore/qcommandlineparser.h \
		../../../qt5.9.2/include/QtCore/qcoreapplication.h \
		../../../qt5.9.2/include/QtCore/qcryptographichash.h \
		../../../qt5.9.2/include/QtCore/qdatastream.h \
		../../../qt5.9.2/include/QtCore/qdatetime.h \
		../../../qt5.9.2/include/QtCore/qdeadlinetimer.h \
		../../../qt5.9.2/include/QtCore/qelapsedtimer.h \
		../../../qt5.9.2/include/QtCore/qdir.h \
		../../../qt5.9.2/include/QtCore/qfileinfo.h \
		../../../qt5.9.2/include/QtCore/qfile.h \
		../../../qt5.9.2/include/QtCore/qfiledevice.h \
		../../../qt5.9.2/include/QtCore/qdiriterator.h \
		../../../qt5.9.2/include/QtCore/qeasingcurve.h \
		../../../qt5.9.2/include/QtCore/qendian.h \
		../../../qt5.9.2/include/QtCore/qeventtransition.h \
		../../../qt5.9.2/include/QtCore/qexception.h \
		../../../qt5.9.2/include/QtCore/qfactoryinterface.h \
		../../../qt5.9.2/include/QtCore/qfileselector.h \
		../../../qt5.9.2/include/QtCore/QObject \
		../../../qt5.9.2/include/QtCore/QStringList \
		../../../qt5.9.2/include/QtCore/qfilesystemwatcher.h \
		../../../qt5.9.2/include/QtCore/qfinalstate.h \
		../../../qt5.9.2/include/QtCore/qfuture.h \
		../../../qt5.9.2/include/QtCore/qfutureinterface.h \
		../../../qt5.9.2/include/QtCore/qrunnable.h \
		../../../qt5.9.2/include/QtCore/qresultstore.h \
		../../../qt5.9.2/include/QtCore/qfuturesynchronizer.h \
		../../../qt5.9.2/include/QtCore/qfuturewatcher.h \
		../../../qt5.9.2/include/QtCore/qhistorystate.h \
		../../../qt5.9.2/include/QtCore/qidentityproxymodel.h \
		../../../qt5.9.2/include/QtCore/qisenum.h \
		../../../qt5.9.2/include/QtCore/qitemselectionmodel.h \
		../../../qt5.9.2/include/QtCore/qjsonarray.h \
		../../../qt5.9.2/include/QtCore/qjsonvalue.h \
		../../../qt5.9.2/include/QtCore/qjsondocument.h \
		../../../qt5.9.2/include/QtCore/qjsonobject.h \
		../../../qt5.9.2/include/QtCore/qlibrary.h \
		../../../qt5.9.2/include/QtCore/qlibraryinfo.h \
		../../../qt5.9.2/include/QtCore/qversionnumber.h \
		../../../qt5.9.2/include/QtCore/qline.h \
		../../../qt5.9.2/include/QtCore/qlinkedlist.h \
		../../../qt5.9.2/include/QtCore/qlockfile.h \
		../../../qt5.9.2/include/QtCore/qloggingcategory.h \
		../../../qt5.9.2/include/QtCore/qmargins.h \
		../../../qt5.9.2/include/QtCore/qmath.h \
		../../../qt5.9.2/include/QtCore/qmessageauthenticationcode.h \
		../../../qt5.9.2/include/QtCore/qmetaobject.h \
		../../../qt5.9.2/include/QtCore/qmimedata.h \
		../../../qt5.9.2/include/QtCore/qmimedatabase.h \
		../../../qt5.9.2/include/QtCore/qmimetype.h \
		../../../qt5.9.2/include/QtCore/qobjectcleanuphandler.h \
		../../../qt5.9.2/include/QtCore/qoperatingsystemversion.h \
		../../../qt5.9.2/include/QtCore/qparallelanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qpauseanimation.h \
		../../../qt5.9.2/include/QtCore/qplugin.h \
		../../../qt5.9.2/include/QtCore/qpointer.h \
		../../../qt5.9.2/include/QtCore/qpluginloader.h \
		../../../qt5.9.2/include/QtCore/qprocess.h \
		../../../qt5.9.2/include/QtCore/qpropertyanimation.h \
		../../../qt5.9.2/include/QtCore/qvariantanimation.h \
		../../../qt5.9.2/include/QtCore/qqueue.h \
		../../../qt5.9.2/include/QtCore/qreadwritelock.h \
		../../../qt5.9.2/include/QtCore/qrect.h \
		../../../qt5.9.2/include/QtCore/qsize.h \
		../../../qt5.9.2/include/QtCore/qregularexpression.h \
		../../../qt5.9.2/include/QtCore/qresource.h \
		../../../qt5.9.2/include/QtCore/qsavefile.h \
		../../../qt5.9.2/include/QtCore/qscopedvaluerollback.h \
		../../../qt5.9.2/include/QtCore/qsemaphore.h \
		../../../qt5.9.2/include/QtCore/qsequentialanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qsettings.h \
		../../../qt5.9.2/include/QtCore/qsharedmemory.h \
		../../../qt5.9.2/include/QtCore/qsignalmapper.h \
		../../../qt5.9.2/include/QtCore/qsignaltransition.h \
		../../../qt5.9.2/include/QtCore/qsocketnotifier.h \
		../../../qt5.9.2/include/QtCore/qsortfilterproxymodel.h \
		../../../qt5.9.2/include/QtCore/qstack.h \
		../../../qt5.9.2/include/QtCore/qstandardpaths.h \
		../../../qt5.9.2/include/QtCore/qstate.h \
		../../../qt5.9.2/include/QtCore/qstatemachine.h \
		../../../qt5.9.2/include/QtCore/qstorageinfo.h \
		../../../qt5.9.2/include/QtCore/qstringlistmodel.h \
		../../../qt5.9.2/include/QtCore/qsystemsemaphore.h \
		../../../qt5.9.2/include/QtCore/qtemporarydir.h \
		../../../qt5.9.2/include/QtCore/QScopedPointer \
		../../../qt5.9.2/include/QtCore/qtemporaryfile.h \
		../../../qt5.9.2/include/QtCore/qtextboundaryfinder.h \
		../../../qt5.9.2/include/QtCore/qtextcodec.h \
		../../../qt5.9.2/include/QtCore/qthread.h \
		../../../qt5.9.2/include/QtCore/qthreadpool.h \
		../../../qt5.9.2/include/QtCore/qthreadstorage.h \
		../../../qt5.9.2/include/QtCore/qtimeline.h \
		../../../qt5.9.2/include/QtCore/qtimer.h \
		../../../qt5.9.2/include/QtCore/qtimezone.h \
		../../../qt5.9.2/include/QtCore/qtranslator.h \
		../../../qt5.9.2/include/QtCore/qtypetraits.h \
		../../../qt5.9.2/include/QtCore/qurl.h \
		../../../qt5.9.2/include/QtCore/qurlquery.h \
		../../../qt5.9.2/include/QtCore/quuid.h \
		../../../qt5.9.2/include/QtCore/qwaitcondition.h \
		../../../qt5.9.2/include/QtCore/qwineventnotifier.h \
		../../../qt5.9.2/include/QtCore/qxmlstream.h \
		../../../qt5.9.2/include/QtCore/qtcoreversion.h \
		pvpanalysis.h \
		../../../qt5.9.2/include/QtGui/QImage \
		../../../qt5.9.2/include/QtGui/qimage.h \
		../../../qt5.9.2/include/QtGui/qtguiglobal.h \
		../../../qt5.9.2/include/QtGui/qtgui-config.h \
		../../../qt5.9.2/include/QtGui/qcolor.h \
		../../../qt5.9.2/include/QtGui/qrgb.h \
		../../../qt5.9.2/include/QtGui/qrgba64.h \
		../../../qt5.9.2/include/QtGui/qpaintdevice.h \
		../../../qt5.9.2/include/QtGui/qwindowdefs.h \
		../../../qt5.9.2/include/QtGui/qwindowdefs_win.h \
		../../../qt5.9.2/include/QtGui/qpixelformat.h \
		../../../qt5.9.2/include/QtGui/qtransform.h \
		../../../qt5.9.2/include/QtGui/qmatrix.h \
		../../../qt5.9.2/include/QtGui/qpolygon.h \
		../../../qt5.9.2/include/QtGui/qregion.h \
		../../../qt5.9.2/include/QtGui/qpainterpath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clusteranalysis.o clusteranalysis.cpp

main.o: main.cpp ../../../qt5.9.2/include/QtCore/QtCore \
		../../../qt5.9.2/include/QtCore/QtCoreDepends \
		../../../qt5.9.2/include/QtCore/qglobal.h \
		../../../qt5.9.2/include/QtCore/qconfig-bootstrapped.h \
		../../../qt5.9.2/include/QtCore/qconfig.h \
		../../../qt5.9.2/include/QtCore/qtcore-config.h \
		../../../qt5.9.2/include/QtCore/qsystemdetection.h \
		../../../qt5.9.2/include/QtCore/qprocessordetection.h \
		../../../qt5.9.2/include/QtCore/qcompilerdetection.h \
		../../../qt5.9.2/include/QtCore/qtypeinfo.h \
		../../../qt5.9.2/include/QtCore/qsysinfo.h \
		../../../qt5.9.2/include/QtCore/qlogging.h \
		../../../qt5.9.2/include/QtCore/qflags.h \
		../../../qt5.9.2/include/QtCore/qatomic.h \
		../../../qt5.9.2/include/QtCore/qbasicatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_bootstrap.h \
		../../../qt5.9.2/include/QtCore/qgenericatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_cxx11.h \
		../../../qt5.9.2/include/QtCore/qatomic_msvc.h \
		../../../qt5.9.2/include/QtCore/qglobalstatic.h \
		../../../qt5.9.2/include/QtCore/qmutex.h \
		../../../qt5.9.2/include/QtCore/qnumeric.h \
		../../../qt5.9.2/include/QtCore/qversiontagging.h \
		../../../qt5.9.2/include/QtCore/qabstractanimation.h \
		../../../qt5.9.2/include/QtCore/qobject.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs.h \
		../../../qt5.9.2/include/QtCore/qnamespace.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs_impl.h \
		../../../qt5.9.2/include/QtCore/qstring.h \
		../../../qt5.9.2/include/QtCore/qchar.h \
		../../../qt5.9.2/include/QtCore/qbytearray.h \
		../../../qt5.9.2/include/QtCore/qrefcount.h \
		../../../qt5.9.2/include/QtCore/qarraydata.h \
		../../../qt5.9.2/include/QtCore/qstringbuilder.h \
		../../../qt5.9.2/include/QtCore/qlist.h \
		../../../qt5.9.2/include/QtCore/qalgorithms.h \
		../../../qt5.9.2/include/QtCore/qiterator.h \
		../../../qt5.9.2/include/QtCore/qhashfunctions.h \
		../../../qt5.9.2/include/QtCore/qpair.h \
		../../../qt5.9.2/include/QtCore/qbytearraylist.h \
		../../../qt5.9.2/include/QtCore/qstringlist.h \
		../../../qt5.9.2/include/QtCore/qregexp.h \
		../../../qt5.9.2/include/QtCore/qstringmatcher.h \
		../../../qt5.9.2/include/QtCore/qcoreevent.h \
		../../../qt5.9.2/include/QtCore/qscopedpointer.h \
		../../../qt5.9.2/include/QtCore/qmetatype.h \
		../../../qt5.9.2/include/QtCore/qvarlengtharray.h \
		../../../qt5.9.2/include/QtCore/qcontainerfwd.h \
		../../../qt5.9.2/include/QtCore/qobject_impl.h \
		../../../qt5.9.2/include/QtCore/qabstracteventdispatcher.h \
		../../../qt5.9.2/include/QtCore/qeventloop.h \
		../../../qt5.9.2/include/QtCore/qabstractitemmodel.h \
		../../../qt5.9.2/include/QtCore/qvariant.h \
		../../../qt5.9.2/include/QtCore/qmap.h \
		../../../qt5.9.2/include/QtCore/qdebug.h \
		../../../qt5.9.2/include/QtCore/qhash.h \
		../../../qt5.9.2/include/QtCore/qtextstream.h \
		../../../qt5.9.2/include/QtCore/qiodevice.h \
		../../../qt5.9.2/include/QtCore/qlocale.h \
		../../../qt5.9.2/include/QtCore/qshareddata.h \
		../../../qt5.9.2/include/QtCore/qvector.h \
		../../../qt5.9.2/include/QtCore/qpoint.h \
		../../../qt5.9.2/include/QtCore/qset.h \
		../../../qt5.9.2/include/QtCore/qcontiguouscache.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer_impl.h \
		../../../qt5.9.2/include/QtCore/qabstractnativeeventfilter.h \
		../../../qt5.9.2/include/QtCore/qabstractproxymodel.h \
		../../../qt5.9.2/include/QtCore/qabstractstate.h \
		../../../qt5.9.2/include/QtCore/qabstracttransition.h \
		../../../qt5.9.2/include/QtCore/qanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qarraydataops.h \
		../../../qt5.9.2/include/QtCore/qarraydatapointer.h \
		../../../qt5.9.2/include/QtCore/qbasictimer.h \
		../../../qt5.9.2/include/QtCore/qbitarray.h \
		../../../qt5.9.2/include/QtCore/qbuffer.h \
		../../../qt5.9.2/include/QtCore/qbytearraymatcher.h \
		../../../qt5.9.2/include/QtCore/qcache.h \
		../../../qt5.9.2/include/QtCore/qcollator.h \
		../../../qt5.9.2/include/QtCore/qcommandlineoption.h \
		../../../qt5.9.2/include/QtCore/qcommandlineparser.h \
		../../../qt5.9.2/include/QtCore/qcoreapplication.h \
		../../../qt5.9.2/include/QtCore/qcryptographichash.h \
		../../../qt5.9.2/include/QtCore/qdatastream.h \
		../../../qt5.9.2/include/QtCore/qdatetime.h \
		../../../qt5.9.2/include/QtCore/qdeadlinetimer.h \
		../../../qt5.9.2/include/QtCore/qelapsedtimer.h \
		../../../qt5.9.2/include/QtCore/qdir.h \
		../../../qt5.9.2/include/QtCore/qfileinfo.h \
		../../../qt5.9.2/include/QtCore/qfile.h \
		../../../qt5.9.2/include/QtCore/qfiledevice.h \
		../../../qt5.9.2/include/QtCore/qdiriterator.h \
		../../../qt5.9.2/include/QtCore/qeasingcurve.h \
		../../../qt5.9.2/include/QtCore/qendian.h \
		../../../qt5.9.2/include/QtCore/qeventtransition.h \
		../../../qt5.9.2/include/QtCore/qexception.h \
		../../../qt5.9.2/include/QtCore/qfactoryinterface.h \
		../../../qt5.9.2/include/QtCore/qfileselector.h \
		../../../qt5.9.2/include/QtCore/QObject \
		../../../qt5.9.2/include/QtCore/QStringList \
		../../../qt5.9.2/include/QtCore/qfilesystemwatcher.h \
		../../../qt5.9.2/include/QtCore/qfinalstate.h \
		../../../qt5.9.2/include/QtCore/qfuture.h \
		../../../qt5.9.2/include/QtCore/qfutureinterface.h \
		../../../qt5.9.2/include/QtCore/qrunnable.h \
		../../../qt5.9.2/include/QtCore/qresultstore.h \
		../../../qt5.9.2/include/QtCore/qfuturesynchronizer.h \
		../../../qt5.9.2/include/QtCore/qfuturewatcher.h \
		../../../qt5.9.2/include/QtCore/qhistorystate.h \
		../../../qt5.9.2/include/QtCore/qidentityproxymodel.h \
		../../../qt5.9.2/include/QtCore/qisenum.h \
		../../../qt5.9.2/include/QtCore/qitemselectionmodel.h \
		../../../qt5.9.2/include/QtCore/qjsonarray.h \
		../../../qt5.9.2/include/QtCore/qjsonvalue.h \
		../../../qt5.9.2/include/QtCore/qjsondocument.h \
		../../../qt5.9.2/include/QtCore/qjsonobject.h \
		../../../qt5.9.2/include/QtCore/qlibrary.h \
		../../../qt5.9.2/include/QtCore/qlibraryinfo.h \
		../../../qt5.9.2/include/QtCore/qversionnumber.h \
		../../../qt5.9.2/include/QtCore/qline.h \
		../../../qt5.9.2/include/QtCore/qlinkedlist.h \
		../../../qt5.9.2/include/QtCore/qlockfile.h \
		../../../qt5.9.2/include/QtCore/qloggingcategory.h \
		../../../qt5.9.2/include/QtCore/qmargins.h \
		../../../qt5.9.2/include/QtCore/qmath.h \
		../../../qt5.9.2/include/QtCore/qmessageauthenticationcode.h \
		../../../qt5.9.2/include/QtCore/qmetaobject.h \
		../../../qt5.9.2/include/QtCore/qmimedata.h \
		../../../qt5.9.2/include/QtCore/qmimedatabase.h \
		../../../qt5.9.2/include/QtCore/qmimetype.h \
		../../../qt5.9.2/include/QtCore/qobjectcleanuphandler.h \
		../../../qt5.9.2/include/QtCore/qoperatingsystemversion.h \
		../../../qt5.9.2/include/QtCore/qparallelanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qpauseanimation.h \
		../../../qt5.9.2/include/QtCore/qplugin.h \
		../../../qt5.9.2/include/QtCore/qpointer.h \
		../../../qt5.9.2/include/QtCore/qpluginloader.h \
		../../../qt5.9.2/include/QtCore/qprocess.h \
		../../../qt5.9.2/include/QtCore/qpropertyanimation.h \
		../../../qt5.9.2/include/QtCore/qvariantanimation.h \
		../../../qt5.9.2/include/QtCore/qqueue.h \
		../../../qt5.9.2/include/QtCore/qreadwritelock.h \
		../../../qt5.9.2/include/QtCore/qrect.h \
		../../../qt5.9.2/include/QtCore/qsize.h \
		../../../qt5.9.2/include/QtCore/qregularexpression.h \
		../../../qt5.9.2/include/QtCore/qresource.h \
		../../../qt5.9.2/include/QtCore/qsavefile.h \
		../../../qt5.9.2/include/QtCore/qscopedvaluerollback.h \
		../../../qt5.9.2/include/QtCore/qsemaphore.h \
		../../../qt5.9.2/include/QtCore/qsequentialanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qsettings.h \
		../../../qt5.9.2/include/QtCore/qsharedmemory.h \
		../../../qt5.9.2/include/QtCore/qsignalmapper.h \
		../../../qt5.9.2/include/QtCore/qsignaltransition.h \
		../../../qt5.9.2/include/QtCore/qsocketnotifier.h \
		../../../qt5.9.2/include/QtCore/qsortfilterproxymodel.h \
		../../../qt5.9.2/include/QtCore/qstack.h \
		../../../qt5.9.2/include/QtCore/qstandardpaths.h \
		../../../qt5.9.2/include/QtCore/qstate.h \
		../../../qt5.9.2/include/QtCore/qstatemachine.h \
		../../../qt5.9.2/include/QtCore/qstorageinfo.h \
		../../../qt5.9.2/include/QtCore/qstringlistmodel.h \
		../../../qt5.9.2/include/QtCore/qsystemsemaphore.h \
		../../../qt5.9.2/include/QtCore/qtemporarydir.h \
		../../../qt5.9.2/include/QtCore/QScopedPointer \
		../../../qt5.9.2/include/QtCore/qtemporaryfile.h \
		../../../qt5.9.2/include/QtCore/qtextboundaryfinder.h \
		../../../qt5.9.2/include/QtCore/qtextcodec.h \
		../../../qt5.9.2/include/QtCore/qthread.h \
		../../../qt5.9.2/include/QtCore/qthreadpool.h \
		../../../qt5.9.2/include/QtCore/qthreadstorage.h \
		../../../qt5.9.2/include/QtCore/qtimeline.h \
		../../../qt5.9.2/include/QtCore/qtimer.h \
		../../../qt5.9.2/include/QtCore/qtimezone.h \
		../../../qt5.9.2/include/QtCore/qtranslator.h \
		../../../qt5.9.2/include/QtCore/qtypetraits.h \
		../../../qt5.9.2/include/QtCore/qurl.h \
		../../../qt5.9.2/include/QtCore/qurlquery.h \
		../../../qt5.9.2/include/QtCore/quuid.h \
		../../../qt5.9.2/include/QtCore/qwaitcondition.h \
		../../../qt5.9.2/include/QtCore/qwineventnotifier.h \
		../../../qt5.9.2/include/QtCore/qxmlstream.h \
		../../../qt5.9.2/include/QtCore/qtcoreversion.h \
		../../../qt5.9.2/include/QtCore/QDebug \
		sasfiles.h \
		pvp.h \
		vectorutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pvp.o: pvp.cpp pvp.h \
		../../../qt5.9.2/include/QtCore/QtCore \
		../../../qt5.9.2/include/QtCore/QtCoreDepends \
		../../../qt5.9.2/include/QtCore/qglobal.h \
		../../../qt5.9.2/include/QtCore/qconfig-bootstrapped.h \
		../../../qt5.9.2/include/QtCore/qconfig.h \
		../../../qt5.9.2/include/QtCore/qtcore-config.h \
		../../../qt5.9.2/include/QtCore/qsystemdetection.h \
		../../../qt5.9.2/include/QtCore/qprocessordetection.h \
		../../../qt5.9.2/include/QtCore/qcompilerdetection.h \
		../../../qt5.9.2/include/QtCore/qtypeinfo.h \
		../../../qt5.9.2/include/QtCore/qsysinfo.h \
		../../../qt5.9.2/include/QtCore/qlogging.h \
		../../../qt5.9.2/include/QtCore/qflags.h \
		../../../qt5.9.2/include/QtCore/qatomic.h \
		../../../qt5.9.2/include/QtCore/qbasicatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_bootstrap.h \
		../../../qt5.9.2/include/QtCore/qgenericatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_cxx11.h \
		../../../qt5.9.2/include/QtCore/qatomic_msvc.h \
		../../../qt5.9.2/include/QtCore/qglobalstatic.h \
		../../../qt5.9.2/include/QtCore/qmutex.h \
		../../../qt5.9.2/include/QtCore/qnumeric.h \
		../../../qt5.9.2/include/QtCore/qversiontagging.h \
		../../../qt5.9.2/include/QtCore/qabstractanimation.h \
		../../../qt5.9.2/include/QtCore/qobject.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs.h \
		../../../qt5.9.2/include/QtCore/qnamespace.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs_impl.h \
		../../../qt5.9.2/include/QtCore/qstring.h \
		../../../qt5.9.2/include/QtCore/qchar.h \
		../../../qt5.9.2/include/QtCore/qbytearray.h \
		../../../qt5.9.2/include/QtCore/qrefcount.h \
		../../../qt5.9.2/include/QtCore/qarraydata.h \
		../../../qt5.9.2/include/QtCore/qstringbuilder.h \
		../../../qt5.9.2/include/QtCore/qlist.h \
		../../../qt5.9.2/include/QtCore/qalgorithms.h \
		../../../qt5.9.2/include/QtCore/qiterator.h \
		../../../qt5.9.2/include/QtCore/qhashfunctions.h \
		../../../qt5.9.2/include/QtCore/qpair.h \
		../../../qt5.9.2/include/QtCore/qbytearraylist.h \
		../../../qt5.9.2/include/QtCore/qstringlist.h \
		../../../qt5.9.2/include/QtCore/qregexp.h \
		../../../qt5.9.2/include/QtCore/qstringmatcher.h \
		../../../qt5.9.2/include/QtCore/qcoreevent.h \
		../../../qt5.9.2/include/QtCore/qscopedpointer.h \
		../../../qt5.9.2/include/QtCore/qmetatype.h \
		../../../qt5.9.2/include/QtCore/qvarlengtharray.h \
		../../../qt5.9.2/include/QtCore/qcontainerfwd.h \
		../../../qt5.9.2/include/QtCore/qobject_impl.h \
		../../../qt5.9.2/include/QtCore/qabstracteventdispatcher.h \
		../../../qt5.9.2/include/QtCore/qeventloop.h \
		../../../qt5.9.2/include/QtCore/qabstractitemmodel.h \
		../../../qt5.9.2/include/QtCore/qvariant.h \
		../../../qt5.9.2/include/QtCore/qmap.h \
		../../../qt5.9.2/include/QtCore/qdebug.h \
		../../../qt5.9.2/include/QtCore/qhash.h \
		../../../qt5.9.2/include/QtCore/qtextstream.h \
		../../../qt5.9.2/include/QtCore/qiodevice.h \
		../../../qt5.9.2/include/QtCore/qlocale.h \
		../../../qt5.9.2/include/QtCore/qshareddata.h \
		../../../qt5.9.2/include/QtCore/qvector.h \
		../../../qt5.9.2/include/QtCore/qpoint.h \
		../../../qt5.9.2/include/QtCore/qset.h \
		../../../qt5.9.2/include/QtCore/qcontiguouscache.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer_impl.h \
		../../../qt5.9.2/include/QtCore/qabstractnativeeventfilter.h \
		../../../qt5.9.2/include/QtCore/qabstractproxymodel.h \
		../../../qt5.9.2/include/QtCore/qabstractstate.h \
		../../../qt5.9.2/include/QtCore/qabstracttransition.h \
		../../../qt5.9.2/include/QtCore/qanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qarraydataops.h \
		../../../qt5.9.2/include/QtCore/qarraydatapointer.h \
		../../../qt5.9.2/include/QtCore/qbasictimer.h \
		../../../qt5.9.2/include/QtCore/qbitarray.h \
		../../../qt5.9.2/include/QtCore/qbuffer.h \
		../../../qt5.9.2/include/QtCore/qbytearraymatcher.h \
		../../../qt5.9.2/include/QtCore/qcache.h \
		../../../qt5.9.2/include/QtCore/qcollator.h \
		../../../qt5.9.2/include/QtCore/qcommandlineoption.h \
		../../../qt5.9.2/include/QtCore/qcommandlineparser.h \
		../../../qt5.9.2/include/QtCore/qcoreapplication.h \
		../../../qt5.9.2/include/QtCore/qcryptographichash.h \
		../../../qt5.9.2/include/QtCore/qdatastream.h \
		../../../qt5.9.2/include/QtCore/qdatetime.h \
		../../../qt5.9.2/include/QtCore/qdeadlinetimer.h \
		../../../qt5.9.2/include/QtCore/qelapsedtimer.h \
		../../../qt5.9.2/include/QtCore/qdir.h \
		../../../qt5.9.2/include/QtCore/qfileinfo.h \
		../../../qt5.9.2/include/QtCore/qfile.h \
		../../../qt5.9.2/include/QtCore/qfiledevice.h \
		../../../qt5.9.2/include/QtCore/qdiriterator.h \
		../../../qt5.9.2/include/QtCore/qeasingcurve.h \
		../../../qt5.9.2/include/QtCore/qendian.h \
		../../../qt5.9.2/include/QtCore/qeventtransition.h \
		../../../qt5.9.2/include/QtCore/qexception.h \
		../../../qt5.9.2/include/QtCore/qfactoryinterface.h \
		../../../qt5.9.2/include/QtCore/qfileselector.h \
		../../../qt5.9.2/include/QtCore/QObject \
		../../../qt5.9.2/include/QtCore/QStringList \
		../../../qt5.9.2/include/QtCore/qfilesystemwatcher.h \
		../../../qt5.9.2/include/QtCore/qfinalstate.h \
		../../../qt5.9.2/include/QtCore/qfuture.h \
		../../../qt5.9.2/include/QtCore/qfutureinterface.h \
		../../../qt5.9.2/include/QtCore/qrunnable.h \
		../../../qt5.9.2/include/QtCore/qresultstore.h \
		../../../qt5.9.2/include/QtCore/qfuturesynchronizer.h \
		../../../qt5.9.2/include/QtCore/qfuturewatcher.h \
		../../../qt5.9.2/include/QtCore/qhistorystate.h \
		../../../qt5.9.2/include/QtCore/qidentityproxymodel.h \
		../../../qt5.9.2/include/QtCore/qisenum.h \
		../../../qt5.9.2/include/QtCore/qitemselectionmodel.h \
		../../../qt5.9.2/include/QtCore/qjsonarray.h \
		../../../qt5.9.2/include/QtCore/qjsonvalue.h \
		../../../qt5.9.2/include/QtCore/qjsondocument.h \
		../../../qt5.9.2/include/QtCore/qjsonobject.h \
		../../../qt5.9.2/include/QtCore/qlibrary.h \
		../../../qt5.9.2/include/QtCore/qlibraryinfo.h \
		../../../qt5.9.2/include/QtCore/qversionnumber.h \
		../../../qt5.9.2/include/QtCore/qline.h \
		../../../qt5.9.2/include/QtCore/qlinkedlist.h \
		../../../qt5.9.2/include/QtCore/qlockfile.h \
		../../../qt5.9.2/include/QtCore/qloggingcategory.h \
		../../../qt5.9.2/include/QtCore/qmargins.h \
		../../../qt5.9.2/include/QtCore/qmath.h \
		../../../qt5.9.2/include/QtCore/qmessageauthenticationcode.h \
		../../../qt5.9.2/include/QtCore/qmetaobject.h \
		../../../qt5.9.2/include/QtCore/qmimedata.h \
		../../../qt5.9.2/include/QtCore/qmimedatabase.h \
		../../../qt5.9.2/include/QtCore/qmimetype.h \
		../../../qt5.9.2/include/QtCore/qobjectcleanuphandler.h \
		../../../qt5.9.2/include/QtCore/qoperatingsystemversion.h \
		../../../qt5.9.2/include/QtCore/qparallelanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qpauseanimation.h \
		../../../qt5.9.2/include/QtCore/qplugin.h \
		../../../qt5.9.2/include/QtCore/qpointer.h \
		../../../qt5.9.2/include/QtCore/qpluginloader.h \
		../../../qt5.9.2/include/QtCore/qprocess.h \
		../../../qt5.9.2/include/QtCore/qpropertyanimation.h \
		../../../qt5.9.2/include/QtCore/qvariantanimation.h \
		../../../qt5.9.2/include/QtCore/qqueue.h \
		../../../qt5.9.2/include/QtCore/qreadwritelock.h \
		../../../qt5.9.2/include/QtCore/qrect.h \
		../../../qt5.9.2/include/QtCore/qsize.h \
		../../../qt5.9.2/include/QtCore/qregularexpression.h \
		../../../qt5.9.2/include/QtCore/qresource.h \
		../../../qt5.9.2/include/QtCore/qsavefile.h \
		../../../qt5.9.2/include/QtCore/qscopedvaluerollback.h \
		../../../qt5.9.2/include/QtCore/qsemaphore.h \
		../../../qt5.9.2/include/QtCore/qsequentialanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qsettings.h \
		../../../qt5.9.2/include/QtCore/qsharedmemory.h \
		../../../qt5.9.2/include/QtCore/qsignalmapper.h \
		../../../qt5.9.2/include/QtCore/qsignaltransition.h \
		../../../qt5.9.2/include/QtCore/qsocketnotifier.h \
		../../../qt5.9.2/include/QtCore/qsortfilterproxymodel.h \
		../../../qt5.9.2/include/QtCore/qstack.h \
		../../../qt5.9.2/include/QtCore/qstandardpaths.h \
		../../../qt5.9.2/include/QtCore/qstate.h \
		../../../qt5.9.2/include/QtCore/qstatemachine.h \
		../../../qt5.9.2/include/QtCore/qstorageinfo.h \
		../../../qt5.9.2/include/QtCore/qstringlistmodel.h \
		../../../qt5.9.2/include/QtCore/qsystemsemaphore.h \
		../../../qt5.9.2/include/QtCore/qtemporarydir.h \
		../../../qt5.9.2/include/QtCore/QScopedPointer \
		../../../qt5.9.2/include/QtCore/qtemporaryfile.h \
		../../../qt5.9.2/include/QtCore/qtextboundaryfinder.h \
		../../../qt5.9.2/include/QtCore/qtextcodec.h \
		../../../qt5.9.2/include/QtCore/qthread.h \
		../../../qt5.9.2/include/QtCore/qthreadpool.h \
		../../../qt5.9.2/include/QtCore/qthreadstorage.h \
		../../../qt5.9.2/include/QtCore/qtimeline.h \
		../../../qt5.9.2/include/QtCore/qtimer.h \
		../../../qt5.9.2/include/QtCore/qtimezone.h \
		../../../qt5.9.2/include/QtCore/qtranslator.h \
		../../../qt5.9.2/include/QtCore/qtypetraits.h \
		../../../qt5.9.2/include/QtCore/qurl.h \
		../../../qt5.9.2/include/QtCore/qurlquery.h \
		../../../qt5.9.2/include/QtCore/quuid.h \
		../../../qt5.9.2/include/QtCore/qwaitcondition.h \
		../../../qt5.9.2/include/QtCore/qwineventnotifier.h \
		../../../qt5.9.2/include/QtCore/qxmlstream.h \
		../../../qt5.9.2/include/QtCore/qtcoreversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pvp.o pvp.cpp

pvpanalysis.o: pvpanalysis.cpp pvpanalysis.h \
		../../../qt5.9.2/include/QtCore/QtCore \
		../../../qt5.9.2/include/QtCore/QtCoreDepends \
		../../../qt5.9.2/include/QtCore/qglobal.h \
		../../../qt5.9.2/include/QtCore/qconfig-bootstrapped.h \
		../../../qt5.9.2/include/QtCore/qconfig.h \
		../../../qt5.9.2/include/QtCore/qtcore-config.h \
		../../../qt5.9.2/include/QtCore/qsystemdetection.h \
		../../../qt5.9.2/include/QtCore/qprocessordetection.h \
		../../../qt5.9.2/include/QtCore/qcompilerdetection.h \
		../../../qt5.9.2/include/QtCore/qtypeinfo.h \
		../../../qt5.9.2/include/QtCore/qsysinfo.h \
		../../../qt5.9.2/include/QtCore/qlogging.h \
		../../../qt5.9.2/include/QtCore/qflags.h \
		../../../qt5.9.2/include/QtCore/qatomic.h \
		../../../qt5.9.2/include/QtCore/qbasicatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_bootstrap.h \
		../../../qt5.9.2/include/QtCore/qgenericatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_cxx11.h \
		../../../qt5.9.2/include/QtCore/qatomic_msvc.h \
		../../../qt5.9.2/include/QtCore/qglobalstatic.h \
		../../../qt5.9.2/include/QtCore/qmutex.h \
		../../../qt5.9.2/include/QtCore/qnumeric.h \
		../../../qt5.9.2/include/QtCore/qversiontagging.h \
		../../../qt5.9.2/include/QtCore/qabstractanimation.h \
		../../../qt5.9.2/include/QtCore/qobject.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs.h \
		../../../qt5.9.2/include/QtCore/qnamespace.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs_impl.h \
		../../../qt5.9.2/include/QtCore/qstring.h \
		../../../qt5.9.2/include/QtCore/qchar.h \
		../../../qt5.9.2/include/QtCore/qbytearray.h \
		../../../qt5.9.2/include/QtCore/qrefcount.h \
		../../../qt5.9.2/include/QtCore/qarraydata.h \
		../../../qt5.9.2/include/QtCore/qstringbuilder.h \
		../../../qt5.9.2/include/QtCore/qlist.h \
		../../../qt5.9.2/include/QtCore/qalgorithms.h \
		../../../qt5.9.2/include/QtCore/qiterator.h \
		../../../qt5.9.2/include/QtCore/qhashfunctions.h \
		../../../qt5.9.2/include/QtCore/qpair.h \
		../../../qt5.9.2/include/QtCore/qbytearraylist.h \
		../../../qt5.9.2/include/QtCore/qstringlist.h \
		../../../qt5.9.2/include/QtCore/qregexp.h \
		../../../qt5.9.2/include/QtCore/qstringmatcher.h \
		../../../qt5.9.2/include/QtCore/qcoreevent.h \
		../../../qt5.9.2/include/QtCore/qscopedpointer.h \
		../../../qt5.9.2/include/QtCore/qmetatype.h \
		../../../qt5.9.2/include/QtCore/qvarlengtharray.h \
		../../../qt5.9.2/include/QtCore/qcontainerfwd.h \
		../../../qt5.9.2/include/QtCore/qobject_impl.h \
		../../../qt5.9.2/include/QtCore/qabstracteventdispatcher.h \
		../../../qt5.9.2/include/QtCore/qeventloop.h \
		../../../qt5.9.2/include/QtCore/qabstractitemmodel.h \
		../../../qt5.9.2/include/QtCore/qvariant.h \
		../../../qt5.9.2/include/QtCore/qmap.h \
		../../../qt5.9.2/include/QtCore/qdebug.h \
		../../../qt5.9.2/include/QtCore/qhash.h \
		../../../qt5.9.2/include/QtCore/qtextstream.h \
		../../../qt5.9.2/include/QtCore/qiodevice.h \
		../../../qt5.9.2/include/QtCore/qlocale.h \
		../../../qt5.9.2/include/QtCore/qshareddata.h \
		../../../qt5.9.2/include/QtCore/qvector.h \
		../../../qt5.9.2/include/QtCore/qpoint.h \
		../../../qt5.9.2/include/QtCore/qset.h \
		../../../qt5.9.2/include/QtCore/qcontiguouscache.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer_impl.h \
		../../../qt5.9.2/include/QtCore/qabstractnativeeventfilter.h \
		../../../qt5.9.2/include/QtCore/qabstractproxymodel.h \
		../../../qt5.9.2/include/QtCore/qabstractstate.h \
		../../../qt5.9.2/include/QtCore/qabstracttransition.h \
		../../../qt5.9.2/include/QtCore/qanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qarraydataops.h \
		../../../qt5.9.2/include/QtCore/qarraydatapointer.h \
		../../../qt5.9.2/include/QtCore/qbasictimer.h \
		../../../qt5.9.2/include/QtCore/qbitarray.h \
		../../../qt5.9.2/include/QtCore/qbuffer.h \
		../../../qt5.9.2/include/QtCore/qbytearraymatcher.h \
		../../../qt5.9.2/include/QtCore/qcache.h \
		../../../qt5.9.2/include/QtCore/qcollator.h \
		../../../qt5.9.2/include/QtCore/qcommandlineoption.h \
		../../../qt5.9.2/include/QtCore/qcommandlineparser.h \
		../../../qt5.9.2/include/QtCore/qcoreapplication.h \
		../../../qt5.9.2/include/QtCore/qcryptographichash.h \
		../../../qt5.9.2/include/QtCore/qdatastream.h \
		../../../qt5.9.2/include/QtCore/qdatetime.h \
		../../../qt5.9.2/include/QtCore/qdeadlinetimer.h \
		../../../qt5.9.2/include/QtCore/qelapsedtimer.h \
		../../../qt5.9.2/include/QtCore/qdir.h \
		../../../qt5.9.2/include/QtCore/qfileinfo.h \
		../../../qt5.9.2/include/QtCore/qfile.h \
		../../../qt5.9.2/include/QtCore/qfiledevice.h \
		../../../qt5.9.2/include/QtCore/qdiriterator.h \
		../../../qt5.9.2/include/QtCore/qeasingcurve.h \
		../../../qt5.9.2/include/QtCore/qendian.h \
		../../../qt5.9.2/include/QtCore/qeventtransition.h \
		../../../qt5.9.2/include/QtCore/qexception.h \
		../../../qt5.9.2/include/QtCore/qfactoryinterface.h \
		../../../qt5.9.2/include/QtCore/qfileselector.h \
		../../../qt5.9.2/include/QtCore/QObject \
		../../../qt5.9.2/include/QtCore/QStringList \
		../../../qt5.9.2/include/QtCore/qfilesystemwatcher.h \
		../../../qt5.9.2/include/QtCore/qfinalstate.h \
		../../../qt5.9.2/include/QtCore/qfuture.h \
		../../../qt5.9.2/include/QtCore/qfutureinterface.h \
		../../../qt5.9.2/include/QtCore/qrunnable.h \
		../../../qt5.9.2/include/QtCore/qresultstore.h \
		../../../qt5.9.2/include/QtCore/qfuturesynchronizer.h \
		../../../qt5.9.2/include/QtCore/qfuturewatcher.h \
		../../../qt5.9.2/include/QtCore/qhistorystate.h \
		../../../qt5.9.2/include/QtCore/qidentityproxymodel.h \
		../../../qt5.9.2/include/QtCore/qisenum.h \
		../../../qt5.9.2/include/QtCore/qitemselectionmodel.h \
		../../../qt5.9.2/include/QtCore/qjsonarray.h \
		../../../qt5.9.2/include/QtCore/qjsonvalue.h \
		../../../qt5.9.2/include/QtCore/qjsondocument.h \
		../../../qt5.9.2/include/QtCore/qjsonobject.h \
		../../../qt5.9.2/include/QtCore/qlibrary.h \
		../../../qt5.9.2/include/QtCore/qlibraryinfo.h \
		../../../qt5.9.2/include/QtCore/qversionnumber.h \
		../../../qt5.9.2/include/QtCore/qline.h \
		../../../qt5.9.2/include/QtCore/qlinkedlist.h \
		../../../qt5.9.2/include/QtCore/qlockfile.h \
		../../../qt5.9.2/include/QtCore/qloggingcategory.h \
		../../../qt5.9.2/include/QtCore/qmargins.h \
		../../../qt5.9.2/include/QtCore/qmath.h \
		../../../qt5.9.2/include/QtCore/qmessageauthenticationcode.h \
		../../../qt5.9.2/include/QtCore/qmetaobject.h \
		../../../qt5.9.2/include/QtCore/qmimedata.h \
		../../../qt5.9.2/include/QtCore/qmimedatabase.h \
		../../../qt5.9.2/include/QtCore/qmimetype.h \
		../../../qt5.9.2/include/QtCore/qobjectcleanuphandler.h \
		../../../qt5.9.2/include/QtCore/qoperatingsystemversion.h \
		../../../qt5.9.2/include/QtCore/qparallelanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qpauseanimation.h \
		../../../qt5.9.2/include/QtCore/qplugin.h \
		../../../qt5.9.2/include/QtCore/qpointer.h \
		../../../qt5.9.2/include/QtCore/qpluginloader.h \
		../../../qt5.9.2/include/QtCore/qprocess.h \
		../../../qt5.9.2/include/QtCore/qpropertyanimation.h \
		../../../qt5.9.2/include/QtCore/qvariantanimation.h \
		../../../qt5.9.2/include/QtCore/qqueue.h \
		../../../qt5.9.2/include/QtCore/qreadwritelock.h \
		../../../qt5.9.2/include/QtCore/qrect.h \
		../../../qt5.9.2/include/QtCore/qsize.h \
		../../../qt5.9.2/include/QtCore/qregularexpression.h \
		../../../qt5.9.2/include/QtCore/qresource.h \
		../../../qt5.9.2/include/QtCore/qsavefile.h \
		../../../qt5.9.2/include/QtCore/qscopedvaluerollback.h \
		../../../qt5.9.2/include/QtCore/qsemaphore.h \
		../../../qt5.9.2/include/QtCore/qsequentialanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qsettings.h \
		../../../qt5.9.2/include/QtCore/qsharedmemory.h \
		../../../qt5.9.2/include/QtCore/qsignalmapper.h \
		../../../qt5.9.2/include/QtCore/qsignaltransition.h \
		../../../qt5.9.2/include/QtCore/qsocketnotifier.h \
		../../../qt5.9.2/include/QtCore/qsortfilterproxymodel.h \
		../../../qt5.9.2/include/QtCore/qstack.h \
		../../../qt5.9.2/include/QtCore/qstandardpaths.h \
		../../../qt5.9.2/include/QtCore/qstate.h \
		../../../qt5.9.2/include/QtCore/qstatemachine.h \
		../../../qt5.9.2/include/QtCore/qstorageinfo.h \
		../../../qt5.9.2/include/QtCore/qstringlistmodel.h \
		../../../qt5.9.2/include/QtCore/qsystemsemaphore.h \
		../../../qt5.9.2/include/QtCore/qtemporarydir.h \
		../../../qt5.9.2/include/QtCore/QScopedPointer \
		../../../qt5.9.2/include/QtCore/qtemporaryfile.h \
		../../../qt5.9.2/include/QtCore/qtextboundaryfinder.h \
		../../../qt5.9.2/include/QtCore/qtextcodec.h \
		../../../qt5.9.2/include/QtCore/qthread.h \
		../../../qt5.9.2/include/QtCore/qthreadpool.h \
		../../../qt5.9.2/include/QtCore/qthreadstorage.h \
		../../../qt5.9.2/include/QtCore/qtimeline.h \
		../../../qt5.9.2/include/QtCore/qtimer.h \
		../../../qt5.9.2/include/QtCore/qtimezone.h \
		../../../qt5.9.2/include/QtCore/qtranslator.h \
		../../../qt5.9.2/include/QtCore/qtypetraits.h \
		../../../qt5.9.2/include/QtCore/qurl.h \
		../../../qt5.9.2/include/QtCore/qurlquery.h \
		../../../qt5.9.2/include/QtCore/quuid.h \
		../../../qt5.9.2/include/QtCore/qwaitcondition.h \
		../../../qt5.9.2/include/QtCore/qwineventnotifier.h \
		../../../qt5.9.2/include/QtCore/qxmlstream.h \
		../../../qt5.9.2/include/QtCore/qtcoreversion.h \
		../../../qt5.9.2/include/QtGui/QImage \
		../../../qt5.9.2/include/QtGui/qimage.h \
		../../../qt5.9.2/include/QtGui/qtguiglobal.h \
		../../../qt5.9.2/include/QtGui/qtgui-config.h \
		../../../qt5.9.2/include/QtGui/qcolor.h \
		../../../qt5.9.2/include/QtGui/qrgb.h \
		../../../qt5.9.2/include/QtGui/qrgba64.h \
		../../../qt5.9.2/include/QtGui/qpaintdevice.h \
		../../../qt5.9.2/include/QtGui/qwindowdefs.h \
		../../../qt5.9.2/include/QtGui/qwindowdefs_win.h \
		../../../qt5.9.2/include/QtGui/qpixelformat.h \
		../../../qt5.9.2/include/QtGui/qtransform.h \
		../../../qt5.9.2/include/QtGui/qmatrix.h \
		../../../qt5.9.2/include/QtGui/qpolygon.h \
		../../../qt5.9.2/include/QtGui/qregion.h \
		../../../qt5.9.2/include/QtGui/qpainterpath.h \
		clusteranalysis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pvpanalysis.o pvpanalysis.cpp

sasfiles.o: sasfiles.cpp sasfiles.h \
		../../../qt5.9.2/include/QtCore/QtCore \
		../../../qt5.9.2/include/QtCore/QtCoreDepends \
		../../../qt5.9.2/include/QtCore/qglobal.h \
		../../../qt5.9.2/include/QtCore/qconfig-bootstrapped.h \
		../../../qt5.9.2/include/QtCore/qconfig.h \
		../../../qt5.9.2/include/QtCore/qtcore-config.h \
		../../../qt5.9.2/include/QtCore/qsystemdetection.h \
		../../../qt5.9.2/include/QtCore/qprocessordetection.h \
		../../../qt5.9.2/include/QtCore/qcompilerdetection.h \
		../../../qt5.9.2/include/QtCore/qtypeinfo.h \
		../../../qt5.9.2/include/QtCore/qsysinfo.h \
		../../../qt5.9.2/include/QtCore/qlogging.h \
		../../../qt5.9.2/include/QtCore/qflags.h \
		../../../qt5.9.2/include/QtCore/qatomic.h \
		../../../qt5.9.2/include/QtCore/qbasicatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_bootstrap.h \
		../../../qt5.9.2/include/QtCore/qgenericatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_cxx11.h \
		../../../qt5.9.2/include/QtCore/qatomic_msvc.h \
		../../../qt5.9.2/include/QtCore/qglobalstatic.h \
		../../../qt5.9.2/include/QtCore/qmutex.h \
		../../../qt5.9.2/include/QtCore/qnumeric.h \
		../../../qt5.9.2/include/QtCore/qversiontagging.h \
		../../../qt5.9.2/include/QtCore/qabstractanimation.h \
		../../../qt5.9.2/include/QtCore/qobject.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs.h \
		../../../qt5.9.2/include/QtCore/qnamespace.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs_impl.h \
		../../../qt5.9.2/include/QtCore/qstring.h \
		../../../qt5.9.2/include/QtCore/qchar.h \
		../../../qt5.9.2/include/QtCore/qbytearray.h \
		../../../qt5.9.2/include/QtCore/qrefcount.h \
		../../../qt5.9.2/include/QtCore/qarraydata.h \
		../../../qt5.9.2/include/QtCore/qstringbuilder.h \
		../../../qt5.9.2/include/QtCore/qlist.h \
		../../../qt5.9.2/include/QtCore/qalgorithms.h \
		../../../qt5.9.2/include/QtCore/qiterator.h \
		../../../qt5.9.2/include/QtCore/qhashfunctions.h \
		../../../qt5.9.2/include/QtCore/qpair.h \
		../../../qt5.9.2/include/QtCore/qbytearraylist.h \
		../../../qt5.9.2/include/QtCore/qstringlist.h \
		../../../qt5.9.2/include/QtCore/qregexp.h \
		../../../qt5.9.2/include/QtCore/qstringmatcher.h \
		../../../qt5.9.2/include/QtCore/qcoreevent.h \
		../../../qt5.9.2/include/QtCore/qscopedpointer.h \
		../../../qt5.9.2/include/QtCore/qmetatype.h \
		../../../qt5.9.2/include/QtCore/qvarlengtharray.h \
		../../../qt5.9.2/include/QtCore/qcontainerfwd.h \
		../../../qt5.9.2/include/QtCore/qobject_impl.h \
		../../../qt5.9.2/include/QtCore/qabstracteventdispatcher.h \
		../../../qt5.9.2/include/QtCore/qeventloop.h \
		../../../qt5.9.2/include/QtCore/qabstractitemmodel.h \
		../../../qt5.9.2/include/QtCore/qvariant.h \
		../../../qt5.9.2/include/QtCore/qmap.h \
		../../../qt5.9.2/include/QtCore/qdebug.h \
		../../../qt5.9.2/include/QtCore/qhash.h \
		../../../qt5.9.2/include/QtCore/qtextstream.h \
		../../../qt5.9.2/include/QtCore/qiodevice.h \
		../../../qt5.9.2/include/QtCore/qlocale.h \
		../../../qt5.9.2/include/QtCore/qshareddata.h \
		../../../qt5.9.2/include/QtCore/qvector.h \
		../../../qt5.9.2/include/QtCore/qpoint.h \
		../../../qt5.9.2/include/QtCore/qset.h \
		../../../qt5.9.2/include/QtCore/qcontiguouscache.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer_impl.h \
		../../../qt5.9.2/include/QtCore/qabstractnativeeventfilter.h \
		../../../qt5.9.2/include/QtCore/qabstractproxymodel.h \
		../../../qt5.9.2/include/QtCore/qabstractstate.h \
		../../../qt5.9.2/include/QtCore/qabstracttransition.h \
		../../../qt5.9.2/include/QtCore/qanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qarraydataops.h \
		../../../qt5.9.2/include/QtCore/qarraydatapointer.h \
		../../../qt5.9.2/include/QtCore/qbasictimer.h \
		../../../qt5.9.2/include/QtCore/qbitarray.h \
		../../../qt5.9.2/include/QtCore/qbuffer.h \
		../../../qt5.9.2/include/QtCore/qbytearraymatcher.h \
		../../../qt5.9.2/include/QtCore/qcache.h \
		../../../qt5.9.2/include/QtCore/qcollator.h \
		../../../qt5.9.2/include/QtCore/qcommandlineoption.h \
		../../../qt5.9.2/include/QtCore/qcommandlineparser.h \
		../../../qt5.9.2/include/QtCore/qcoreapplication.h \
		../../../qt5.9.2/include/QtCore/qcryptographichash.h \
		../../../qt5.9.2/include/QtCore/qdatastream.h \
		../../../qt5.9.2/include/QtCore/qdatetime.h \
		../../../qt5.9.2/include/QtCore/qdeadlinetimer.h \
		../../../qt5.9.2/include/QtCore/qelapsedtimer.h \
		../../../qt5.9.2/include/QtCore/qdir.h \
		../../../qt5.9.2/include/QtCore/qfileinfo.h \
		../../../qt5.9.2/include/QtCore/qfile.h \
		../../../qt5.9.2/include/QtCore/qfiledevice.h \
		../../../qt5.9.2/include/QtCore/qdiriterator.h \
		../../../qt5.9.2/include/QtCore/qeasingcurve.h \
		../../../qt5.9.2/include/QtCore/qendian.h \
		../../../qt5.9.2/include/QtCore/qeventtransition.h \
		../../../qt5.9.2/include/QtCore/qexception.h \
		../../../qt5.9.2/include/QtCore/qfactoryinterface.h \
		../../../qt5.9.2/include/QtCore/qfileselector.h \
		../../../qt5.9.2/include/QtCore/QObject \
		../../../qt5.9.2/include/QtCore/QStringList \
		../../../qt5.9.2/include/QtCore/qfilesystemwatcher.h \
		../../../qt5.9.2/include/QtCore/qfinalstate.h \
		../../../qt5.9.2/include/QtCore/qfuture.h \
		../../../qt5.9.2/include/QtCore/qfutureinterface.h \
		../../../qt5.9.2/include/QtCore/qrunnable.h \
		../../../qt5.9.2/include/QtCore/qresultstore.h \
		../../../qt5.9.2/include/QtCore/qfuturesynchronizer.h \
		../../../qt5.9.2/include/QtCore/qfuturewatcher.h \
		../../../qt5.9.2/include/QtCore/qhistorystate.h \
		../../../qt5.9.2/include/QtCore/qidentityproxymodel.h \
		../../../qt5.9.2/include/QtCore/qisenum.h \
		../../../qt5.9.2/include/QtCore/qitemselectionmodel.h \
		../../../qt5.9.2/include/QtCore/qjsonarray.h \
		../../../qt5.9.2/include/QtCore/qjsonvalue.h \
		../../../qt5.9.2/include/QtCore/qjsondocument.h \
		../../../qt5.9.2/include/QtCore/qjsonobject.h \
		../../../qt5.9.2/include/QtCore/qlibrary.h \
		../../../qt5.9.2/include/QtCore/qlibraryinfo.h \
		../../../qt5.9.2/include/QtCore/qversionnumber.h \
		../../../qt5.9.2/include/QtCore/qline.h \
		../../../qt5.9.2/include/QtCore/qlinkedlist.h \
		../../../qt5.9.2/include/QtCore/qlockfile.h \
		../../../qt5.9.2/include/QtCore/qloggingcategory.h \
		../../../qt5.9.2/include/QtCore/qmargins.h \
		../../../qt5.9.2/include/QtCore/qmath.h \
		../../../qt5.9.2/include/QtCore/qmessageauthenticationcode.h \
		../../../qt5.9.2/include/QtCore/qmetaobject.h \
		../../../qt5.9.2/include/QtCore/qmimedata.h \
		../../../qt5.9.2/include/QtCore/qmimedatabase.h \
		../../../qt5.9.2/include/QtCore/qmimetype.h \
		../../../qt5.9.2/include/QtCore/qobjectcleanuphandler.h \
		../../../qt5.9.2/include/QtCore/qoperatingsystemversion.h \
		../../../qt5.9.2/include/QtCore/qparallelanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qpauseanimation.h \
		../../../qt5.9.2/include/QtCore/qplugin.h \
		../../../qt5.9.2/include/QtCore/qpointer.h \
		../../../qt5.9.2/include/QtCore/qpluginloader.h \
		../../../qt5.9.2/include/QtCore/qprocess.h \
		../../../qt5.9.2/include/QtCore/qpropertyanimation.h \
		../../../qt5.9.2/include/QtCore/qvariantanimation.h \
		../../../qt5.9.2/include/QtCore/qqueue.h \
		../../../qt5.9.2/include/QtCore/qreadwritelock.h \
		../../../qt5.9.2/include/QtCore/qrect.h \
		../../../qt5.9.2/include/QtCore/qsize.h \
		../../../qt5.9.2/include/QtCore/qregularexpression.h \
		../../../qt5.9.2/include/QtCore/qresource.h \
		../../../qt5.9.2/include/QtCore/qsavefile.h \
		../../../qt5.9.2/include/QtCore/qscopedvaluerollback.h \
		../../../qt5.9.2/include/QtCore/qsemaphore.h \
		../../../qt5.9.2/include/QtCore/qsequentialanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qsettings.h \
		../../../qt5.9.2/include/QtCore/qsharedmemory.h \
		../../../qt5.9.2/include/QtCore/qsignalmapper.h \
		../../../qt5.9.2/include/QtCore/qsignaltransition.h \
		../../../qt5.9.2/include/QtCore/qsocketnotifier.h \
		../../../qt5.9.2/include/QtCore/qsortfilterproxymodel.h \
		../../../qt5.9.2/include/QtCore/qstack.h \
		../../../qt5.9.2/include/QtCore/qstandardpaths.h \
		../../../qt5.9.2/include/QtCore/qstate.h \
		../../../qt5.9.2/include/QtCore/qstatemachine.h \
		../../../qt5.9.2/include/QtCore/qstorageinfo.h \
		../../../qt5.9.2/include/QtCore/qstringlistmodel.h \
		../../../qt5.9.2/include/QtCore/qsystemsemaphore.h \
		../../../qt5.9.2/include/QtCore/qtemporarydir.h \
		../../../qt5.9.2/include/QtCore/QScopedPointer \
		../../../qt5.9.2/include/QtCore/qtemporaryfile.h \
		../../../qt5.9.2/include/QtCore/qtextboundaryfinder.h \
		../../../qt5.9.2/include/QtCore/qtextcodec.h \
		../../../qt5.9.2/include/QtCore/qthread.h \
		../../../qt5.9.2/include/QtCore/qthreadpool.h \
		../../../qt5.9.2/include/QtCore/qthreadstorage.h \
		../../../qt5.9.2/include/QtCore/qtimeline.h \
		../../../qt5.9.2/include/QtCore/qtimer.h \
		../../../qt5.9.2/include/QtCore/qtimezone.h \
		../../../qt5.9.2/include/QtCore/qtranslator.h \
		../../../qt5.9.2/include/QtCore/qtypetraits.h \
		../../../qt5.9.2/include/QtCore/qurl.h \
		../../../qt5.9.2/include/QtCore/qurlquery.h \
		../../../qt5.9.2/include/QtCore/quuid.h \
		../../../qt5.9.2/include/QtCore/qwaitcondition.h \
		../../../qt5.9.2/include/QtCore/qwineventnotifier.h \
		../../../qt5.9.2/include/QtCore/qxmlstream.h \
		../../../qt5.9.2/include/QtCore/qtcoreversion.h \
		pvp.h \
		vectorutils.h \
		pvpanalysis.h \
		../../../qt5.9.2/include/QtGui/QImage \
		../../../qt5.9.2/include/QtGui/qimage.h \
		../../../qt5.9.2/include/QtGui/qtguiglobal.h \
		../../../qt5.9.2/include/QtGui/qtgui-config.h \
		../../../qt5.9.2/include/QtGui/qcolor.h \
		../../../qt5.9.2/include/QtGui/qrgb.h \
		../../../qt5.9.2/include/QtGui/qrgba64.h \
		../../../qt5.9.2/include/QtGui/qpaintdevice.h \
		../../../qt5.9.2/include/QtGui/qwindowdefs.h \
		../../../qt5.9.2/include/QtGui/qwindowdefs_win.h \
		../../../qt5.9.2/include/QtGui/qpixelformat.h \
		../../../qt5.9.2/include/QtGui/qtransform.h \
		../../../qt5.9.2/include/QtGui/qmatrix.h \
		../../../qt5.9.2/include/QtGui/qpolygon.h \
		../../../qt5.9.2/include/QtGui/qregion.h \
		../../../qt5.9.2/include/QtGui/qpainterpath.h \
		clusteranalysis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sasfiles.o sasfiles.cpp

vectorutils.o: vectorutils.cpp vectorutils.h \
		../../../qt5.9.2/include/QtCore/QtCore \
		../../../qt5.9.2/include/QtCore/QtCoreDepends \
		../../../qt5.9.2/include/QtCore/qglobal.h \
		../../../qt5.9.2/include/QtCore/qconfig-bootstrapped.h \
		../../../qt5.9.2/include/QtCore/qconfig.h \
		../../../qt5.9.2/include/QtCore/qtcore-config.h \
		../../../qt5.9.2/include/QtCore/qsystemdetection.h \
		../../../qt5.9.2/include/QtCore/qprocessordetection.h \
		../../../qt5.9.2/include/QtCore/qcompilerdetection.h \
		../../../qt5.9.2/include/QtCore/qtypeinfo.h \
		../../../qt5.9.2/include/QtCore/qsysinfo.h \
		../../../qt5.9.2/include/QtCore/qlogging.h \
		../../../qt5.9.2/include/QtCore/qflags.h \
		../../../qt5.9.2/include/QtCore/qatomic.h \
		../../../qt5.9.2/include/QtCore/qbasicatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_bootstrap.h \
		../../../qt5.9.2/include/QtCore/qgenericatomic.h \
		../../../qt5.9.2/include/QtCore/qatomic_cxx11.h \
		../../../qt5.9.2/include/QtCore/qatomic_msvc.h \
		../../../qt5.9.2/include/QtCore/qglobalstatic.h \
		../../../qt5.9.2/include/QtCore/qmutex.h \
		../../../qt5.9.2/include/QtCore/qnumeric.h \
		../../../qt5.9.2/include/QtCore/qversiontagging.h \
		../../../qt5.9.2/include/QtCore/qabstractanimation.h \
		../../../qt5.9.2/include/QtCore/qobject.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs.h \
		../../../qt5.9.2/include/QtCore/qnamespace.h \
		../../../qt5.9.2/include/QtCore/qobjectdefs_impl.h \
		../../../qt5.9.2/include/QtCore/qstring.h \
		../../../qt5.9.2/include/QtCore/qchar.h \
		../../../qt5.9.2/include/QtCore/qbytearray.h \
		../../../qt5.9.2/include/QtCore/qrefcount.h \
		../../../qt5.9.2/include/QtCore/qarraydata.h \
		../../../qt5.9.2/include/QtCore/qstringbuilder.h \
		../../../qt5.9.2/include/QtCore/qlist.h \
		../../../qt5.9.2/include/QtCore/qalgorithms.h \
		../../../qt5.9.2/include/QtCore/qiterator.h \
		../../../qt5.9.2/include/QtCore/qhashfunctions.h \
		../../../qt5.9.2/include/QtCore/qpair.h \
		../../../qt5.9.2/include/QtCore/qbytearraylist.h \
		../../../qt5.9.2/include/QtCore/qstringlist.h \
		../../../qt5.9.2/include/QtCore/qregexp.h \
		../../../qt5.9.2/include/QtCore/qstringmatcher.h \
		../../../qt5.9.2/include/QtCore/qcoreevent.h \
		../../../qt5.9.2/include/QtCore/qscopedpointer.h \
		../../../qt5.9.2/include/QtCore/qmetatype.h \
		../../../qt5.9.2/include/QtCore/qvarlengtharray.h \
		../../../qt5.9.2/include/QtCore/qcontainerfwd.h \
		../../../qt5.9.2/include/QtCore/qobject_impl.h \
		../../../qt5.9.2/include/QtCore/qabstracteventdispatcher.h \
		../../../qt5.9.2/include/QtCore/qeventloop.h \
		../../../qt5.9.2/include/QtCore/qabstractitemmodel.h \
		../../../qt5.9.2/include/QtCore/qvariant.h \
		../../../qt5.9.2/include/QtCore/qmap.h \
		../../../qt5.9.2/include/QtCore/qdebug.h \
		../../../qt5.9.2/include/QtCore/qhash.h \
		../../../qt5.9.2/include/QtCore/qtextstream.h \
		../../../qt5.9.2/include/QtCore/qiodevice.h \
		../../../qt5.9.2/include/QtCore/qlocale.h \
		../../../qt5.9.2/include/QtCore/qshareddata.h \
		../../../qt5.9.2/include/QtCore/qvector.h \
		../../../qt5.9.2/include/QtCore/qpoint.h \
		../../../qt5.9.2/include/QtCore/qset.h \
		../../../qt5.9.2/include/QtCore/qcontiguouscache.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer.h \
		../../../qt5.9.2/include/QtCore/qsharedpointer_impl.h \
		../../../qt5.9.2/include/QtCore/qabstractnativeeventfilter.h \
		../../../qt5.9.2/include/QtCore/qabstractproxymodel.h \
		../../../qt5.9.2/include/QtCore/qabstractstate.h \
		../../../qt5.9.2/include/QtCore/qabstracttransition.h \
		../../../qt5.9.2/include/QtCore/qanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qarraydataops.h \
		../../../qt5.9.2/include/QtCore/qarraydatapointer.h \
		../../../qt5.9.2/include/QtCore/qbasictimer.h \
		../../../qt5.9.2/include/QtCore/qbitarray.h \
		../../../qt5.9.2/include/QtCore/qbuffer.h \
		../../../qt5.9.2/include/QtCore/qbytearraymatcher.h \
		../../../qt5.9.2/include/QtCore/qcache.h \
		../../../qt5.9.2/include/QtCore/qcollator.h \
		../../../qt5.9.2/include/QtCore/qcommandlineoption.h \
		../../../qt5.9.2/include/QtCore/qcommandlineparser.h \
		../../../qt5.9.2/include/QtCore/qcoreapplication.h \
		../../../qt5.9.2/include/QtCore/qcryptographichash.h \
		../../../qt5.9.2/include/QtCore/qdatastream.h \
		../../../qt5.9.2/include/QtCore/qdatetime.h \
		../../../qt5.9.2/include/QtCore/qdeadlinetimer.h \
		../../../qt5.9.2/include/QtCore/qelapsedtimer.h \
		../../../qt5.9.2/include/QtCore/qdir.h \
		../../../qt5.9.2/include/QtCore/qfileinfo.h \
		../../../qt5.9.2/include/QtCore/qfile.h \
		../../../qt5.9.2/include/QtCore/qfiledevice.h \
		../../../qt5.9.2/include/QtCore/qdiriterator.h \
		../../../qt5.9.2/include/QtCore/qeasingcurve.h \
		../../../qt5.9.2/include/QtCore/qendian.h \
		../../../qt5.9.2/include/QtCore/qeventtransition.h \
		../../../qt5.9.2/include/QtCore/qexception.h \
		../../../qt5.9.2/include/QtCore/qfactoryinterface.h \
		../../../qt5.9.2/include/QtCore/qfileselector.h \
		../../../qt5.9.2/include/QtCore/QObject \
		../../../qt5.9.2/include/QtCore/QStringList \
		../../../qt5.9.2/include/QtCore/qfilesystemwatcher.h \
		../../../qt5.9.2/include/QtCore/qfinalstate.h \
		../../../qt5.9.2/include/QtCore/qfuture.h \
		../../../qt5.9.2/include/QtCore/qfutureinterface.h \
		../../../qt5.9.2/include/QtCore/qrunnable.h \
		../../../qt5.9.2/include/QtCore/qresultstore.h \
		../../../qt5.9.2/include/QtCore/qfuturesynchronizer.h \
		../../../qt5.9.2/include/QtCore/qfuturewatcher.h \
		../../../qt5.9.2/include/QtCore/qhistorystate.h \
		../../../qt5.9.2/include/QtCore/qidentityproxymodel.h \
		../../../qt5.9.2/include/QtCore/qisenum.h \
		../../../qt5.9.2/include/QtCore/qitemselectionmodel.h \
		../../../qt5.9.2/include/QtCore/qjsonarray.h \
		../../../qt5.9.2/include/QtCore/qjsonvalue.h \
		../../../qt5.9.2/include/QtCore/qjsondocument.h \
		../../../qt5.9.2/include/QtCore/qjsonobject.h \
		../../../qt5.9.2/include/QtCore/qlibrary.h \
		../../../qt5.9.2/include/QtCore/qlibraryinfo.h \
		../../../qt5.9.2/include/QtCore/qversionnumber.h \
		../../../qt5.9.2/include/QtCore/qline.h \
		../../../qt5.9.2/include/QtCore/qlinkedlist.h \
		../../../qt5.9.2/include/QtCore/qlockfile.h \
		../../../qt5.9.2/include/QtCore/qloggingcategory.h \
		../../../qt5.9.2/include/QtCore/qmargins.h \
		../../../qt5.9.2/include/QtCore/qmath.h \
		../../../qt5.9.2/include/QtCore/qmessageauthenticationcode.h \
		../../../qt5.9.2/include/QtCore/qmetaobject.h \
		../../../qt5.9.2/include/QtCore/qmimedata.h \
		../../../qt5.9.2/include/QtCore/qmimedatabase.h \
		../../../qt5.9.2/include/QtCore/qmimetype.h \
		../../../qt5.9.2/include/QtCore/qobjectcleanuphandler.h \
		../../../qt5.9.2/include/QtCore/qoperatingsystemversion.h \
		../../../qt5.9.2/include/QtCore/qparallelanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qpauseanimation.h \
		../../../qt5.9.2/include/QtCore/qplugin.h \
		../../../qt5.9.2/include/QtCore/qpointer.h \
		../../../qt5.9.2/include/QtCore/qpluginloader.h \
		../../../qt5.9.2/include/QtCore/qprocess.h \
		../../../qt5.9.2/include/QtCore/qpropertyanimation.h \
		../../../qt5.9.2/include/QtCore/qvariantanimation.h \
		../../../qt5.9.2/include/QtCore/qqueue.h \
		../../../qt5.9.2/include/QtCore/qreadwritelock.h \
		../../../qt5.9.2/include/QtCore/qrect.h \
		../../../qt5.9.2/include/QtCore/qsize.h \
		../../../qt5.9.2/include/QtCore/qregularexpression.h \
		../../../qt5.9.2/include/QtCore/qresource.h \
		../../../qt5.9.2/include/QtCore/qsavefile.h \
		../../../qt5.9.2/include/QtCore/qscopedvaluerollback.h \
		../../../qt5.9.2/include/QtCore/qsemaphore.h \
		../../../qt5.9.2/include/QtCore/qsequentialanimationgroup.h \
		../../../qt5.9.2/include/QtCore/qsettings.h \
		../../../qt5.9.2/include/QtCore/qsharedmemory.h \
		../../../qt5.9.2/include/QtCore/qsignalmapper.h \
		../../../qt5.9.2/include/QtCore/qsignaltransition.h \
		../../../qt5.9.2/include/QtCore/qsocketnotifier.h \
		../../../qt5.9.2/include/QtCore/qsortfilterproxymodel.h \
		../../../qt5.9.2/include/QtCore/qstack.h \
		../../../qt5.9.2/include/QtCore/qstandardpaths.h \
		../../../qt5.9.2/include/QtCore/qstate.h \
		../../../qt5.9.2/include/QtCore/qstatemachine.h \
		../../../qt5.9.2/include/QtCore/qstorageinfo.h \
		../../../qt5.9.2/include/QtCore/qstringlistmodel.h \
		../../../qt5.9.2/include/QtCore/qsystemsemaphore.h \
		../../../qt5.9.2/include/QtCore/qtemporarydir.h \
		../../../qt5.9.2/include/QtCore/QScopedPointer \
		../../../qt5.9.2/include/QtCore/qtemporaryfile.h \
		../../../qt5.9.2/include/QtCore/qtextboundaryfinder.h \
		../../../qt5.9.2/include/QtCore/qtextcodec.h \
		../../../qt5.9.2/include/QtCore/qthread.h \
		../../../qt5.9.2/include/QtCore/qthreadpool.h \
		../../../qt5.9.2/include/QtCore/qthreadstorage.h \
		../../../qt5.9.2/include/QtCore/qtimeline.h \
		../../../qt5.9.2/include/QtCore/qtimer.h \
		../../../qt5.9.2/include/QtCore/qtimezone.h \
		../../../qt5.9.2/include/QtCore/qtranslator.h \
		../../../qt5.9.2/include/QtCore/qtypetraits.h \
		../../../qt5.9.2/include/QtCore/qurl.h \
		../../../qt5.9.2/include/QtCore/qurlquery.h \
		../../../qt5.9.2/include/QtCore/quuid.h \
		../../../qt5.9.2/include/QtCore/qwaitcondition.h \
		../../../qt5.9.2/include/QtCore/qwineventnotifier.h \
		../../../qt5.9.2/include/QtCore/qxmlstream.h \
		../../../qt5.9.2/include/QtCore/qtcoreversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vectorutils.o vectorutils.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

